/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface PrismXXBridgeInterface extends utils.Interface {
  functions: {
    "adminSetAsset(address)": FunctionFragment;
    "adminSetLedger(address)": FunctionFragment;
    "asset_contract()": FunctionFragment;
    "computeERC1155AssetType(address,uint256)": FunctionFragment;
    "computeERC20AssetType(address)": FunctionFragment;
    "computeERC721AssetType(address,uint256)": FunctionFragment;
    "depositFRA(bytes)": FunctionFragment;
    "depositFRC1155(address,bytes,uint256,uint256)": FunctionFragment;
    "depositFRC20(address,bytes,uint256)": FunctionFragment;
    "depositFRC721(address,bytes,uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "ledger_contract()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawAsset(bytes32,bytes,address,uint256,bytes)": FunctionFragment;
    "withdrawFRA(address,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "adminSetAsset"
      | "adminSetLedger"
      | "asset_contract"
      | "computeERC1155AssetType"
      | "computeERC20AssetType"
      | "computeERC721AssetType"
      | "depositFRA"
      | "depositFRC1155"
      | "depositFRC20"
      | "depositFRC721"
      | "initialize"
      | "ledger_contract"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "withdrawAsset"
      | "withdrawFRA"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "adminSetAsset",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetLedger",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "asset_contract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeERC1155AssetType",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "computeERC20AssetType",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "computeERC721AssetType",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFRA",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFRC1155",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFRC20",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFRC721",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ledger_contract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAsset",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFRA",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminSetAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetLedger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "asset_contract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeERC1155AssetType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeERC20AssetType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeERC721AssetType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFRA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositFRC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFRC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFRC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ledger_contract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFRA",
    data: BytesLike
  ): Result;

  events: {
    "DepositAsset(bytes32,bytes,uint256,uint8,uint256)": EventFragment;
    "DepositFRA(address,bytes,uint256)": EventFragment;
    "DepositFRC1155(address,address,bytes,uint256,uint256)": EventFragment;
    "DepositFRC20(address,address,bytes,uint256)": EventFragment;
    "DepositFRC721(address,address,bytes,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "WithdrawFRA(bytes,address,uint256)": EventFragment;
    "WithdrawFRC1155(address,bytes,address,uint256,uint256)": EventFragment;
    "WithdrawFRC20(address,bytes,address,uint256)": EventFragment;
    "WithdrawFRC721(address,bytes,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositAsset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositFRA"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositFRC1155"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositFRC20"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositFRC721"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawFRA"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawFRC1155"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawFRC20"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawFRC721"): EventFragment;
}

export interface DepositAssetEventObject {
  asset: string;
  receiver: string;
  amount: BigNumber;
  decimal: number;
  max_supply: BigNumber;
}
export type DepositAssetEvent = TypedEvent<
  [string, string, BigNumber, number, BigNumber],
  DepositAssetEventObject
>;

export type DepositAssetEventFilter = TypedEventFilter<DepositAssetEvent>;

export interface DepositFRAEventObject {
  _from: string;
  _to: string;
  _amount: BigNumber;
}
export type DepositFRAEvent = TypedEvent<
  [string, string, BigNumber],
  DepositFRAEventObject
>;

export type DepositFRAEventFilter = TypedEventFilter<DepositFRAEvent>;

export interface DepositFRC1155EventObject {
  _addr: string;
  _from: string;
  _to: string;
  _id: BigNumber;
  amount: BigNumber;
}
export type DepositFRC1155Event = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  DepositFRC1155EventObject
>;

export type DepositFRC1155EventFilter = TypedEventFilter<DepositFRC1155Event>;

export interface DepositFRC20EventObject {
  _frc20: string;
  _from: string;
  _to: string;
  _amount: BigNumber;
}
export type DepositFRC20Event = TypedEvent<
  [string, string, string, BigNumber],
  DepositFRC20EventObject
>;

export type DepositFRC20EventFilter = TypedEventFilter<DepositFRC20Event>;

export interface DepositFRC721EventObject {
  _addr: string;
  _from: string;
  _to: string;
  _id: BigNumber;
}
export type DepositFRC721Event = TypedEvent<
  [string, string, string, BigNumber],
  DepositFRC721EventObject
>;

export type DepositFRC721EventFilter = TypedEventFilter<DepositFRC721Event>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface WithdrawFRAEventObject {
  _from: string;
  _to: string;
  _amount: BigNumber;
}
export type WithdrawFRAEvent = TypedEvent<
  [string, string, BigNumber],
  WithdrawFRAEventObject
>;

export type WithdrawFRAEventFilter = TypedEventFilter<WithdrawFRAEvent>;

export interface WithdrawFRC1155EventObject {
  _frc20: string;
  _from: string;
  _to: string;
  _id: BigNumber;
  _amount: BigNumber;
}
export type WithdrawFRC1155Event = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  WithdrawFRC1155EventObject
>;

export type WithdrawFRC1155EventFilter = TypedEventFilter<WithdrawFRC1155Event>;

export interface WithdrawFRC20EventObject {
  _frc20: string;
  _from: string;
  _to: string;
  _amount: BigNumber;
}
export type WithdrawFRC20Event = TypedEvent<
  [string, string, string, BigNumber],
  WithdrawFRC20EventObject
>;

export type WithdrawFRC20EventFilter = TypedEventFilter<WithdrawFRC20Event>;

export interface WithdrawFRC721EventObject {
  _frc20: string;
  _from: string;
  _to: string;
  _id: BigNumber;
}
export type WithdrawFRC721Event = TypedEvent<
  [string, string, string, BigNumber],
  WithdrawFRC721EventObject
>;

export type WithdrawFRC721EventFilter = TypedEventFilter<WithdrawFRC721Event>;

export interface PrismXXBridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PrismXXBridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    adminSetAsset(
      _asset_contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    adminSetLedger(
      _ledger_contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    asset_contract(overrides?: CallOverrides): Promise<[string]>;

    computeERC1155AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { result: string }>;

    computeERC20AssetType(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    computeERC721AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    depositFRA(
      _to: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositFRC1155(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositFRC20(
      _frc20: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositFRC721(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ledger_contract(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawAsset(
      _asset: PromiseOrValue<BytesLike>,
      _from: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFRA(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  adminSetAsset(
    _asset_contract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  adminSetLedger(
    _ledger_contract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  asset_contract(overrides?: CallOverrides): Promise<string>;

  computeERC1155AssetType(
    addr: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  computeERC20AssetType(
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  computeERC721AssetType(
    addr: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  depositFRA(
    _to: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositFRC1155(
    _addr: PromiseOrValue<string>,
    _to: PromiseOrValue<BytesLike>,
    _id: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositFRC20(
    _frc20: PromiseOrValue<string>,
    _to: PromiseOrValue<BytesLike>,
    _value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositFRC721(
    _addr: PromiseOrValue<string>,
    _to: PromiseOrValue<BytesLike>,
    _id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ledger_contract(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawAsset(
    _asset: PromiseOrValue<BytesLike>,
    _from: PromiseOrValue<BytesLike>,
    _to: PromiseOrValue<string>,
    _value: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFRA(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    adminSetAsset(
      _asset_contract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    adminSetLedger(
      _ledger_contract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    asset_contract(overrides?: CallOverrides): Promise<string>;

    computeERC1155AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    computeERC20AssetType(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    computeERC721AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    depositFRA(
      _to: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositFRC1155(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositFRC20(
      _frc20: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositFRC721(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(overrides?: CallOverrides): Promise<void>;

    ledger_contract(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAsset(
      _asset: PromiseOrValue<BytesLike>,
      _from: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFRA(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositAsset(bytes32,bytes,uint256,uint8,uint256)"(
      asset?: null,
      receiver?: null,
      amount?: null,
      decimal?: null,
      max_supply?: null
    ): DepositAssetEventFilter;
    DepositAsset(
      asset?: null,
      receiver?: null,
      amount?: null,
      decimal?: null,
      max_supply?: null
    ): DepositAssetEventFilter;

    "DepositFRA(address,bytes,uint256)"(
      _from?: null,
      _to?: null,
      _amount?: null
    ): DepositFRAEventFilter;
    DepositFRA(_from?: null, _to?: null, _amount?: null): DepositFRAEventFilter;

    "DepositFRC1155(address,address,bytes,uint256,uint256)"(
      _addr?: null,
      _from?: null,
      _to?: null,
      _id?: null,
      amount?: null
    ): DepositFRC1155EventFilter;
    DepositFRC1155(
      _addr?: null,
      _from?: null,
      _to?: null,
      _id?: null,
      amount?: null
    ): DepositFRC1155EventFilter;

    "DepositFRC20(address,address,bytes,uint256)"(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _amount?: null
    ): DepositFRC20EventFilter;
    DepositFRC20(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _amount?: null
    ): DepositFRC20EventFilter;

    "DepositFRC721(address,address,bytes,uint256)"(
      _addr?: null,
      _from?: null,
      _to?: null,
      _id?: null
    ): DepositFRC721EventFilter;
    DepositFRC721(
      _addr?: null,
      _from?: null,
      _to?: null,
      _id?: null
    ): DepositFRC721EventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "WithdrawFRA(bytes,address,uint256)"(
      _from?: null,
      _to?: null,
      _amount?: null
    ): WithdrawFRAEventFilter;
    WithdrawFRA(
      _from?: null,
      _to?: null,
      _amount?: null
    ): WithdrawFRAEventFilter;

    "WithdrawFRC1155(address,bytes,address,uint256,uint256)"(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _id?: null,
      _amount?: null
    ): WithdrawFRC1155EventFilter;
    WithdrawFRC1155(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _id?: null,
      _amount?: null
    ): WithdrawFRC1155EventFilter;

    "WithdrawFRC20(address,bytes,address,uint256)"(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _amount?: null
    ): WithdrawFRC20EventFilter;
    WithdrawFRC20(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _amount?: null
    ): WithdrawFRC20EventFilter;

    "WithdrawFRC721(address,bytes,address,uint256)"(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _id?: null
    ): WithdrawFRC721EventFilter;
    WithdrawFRC721(
      _frc20?: null,
      _from?: null,
      _to?: null,
      _id?: null
    ): WithdrawFRC721EventFilter;
  };

  estimateGas: {
    adminSetAsset(
      _asset_contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    adminSetLedger(
      _ledger_contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    asset_contract(overrides?: CallOverrides): Promise<BigNumber>;

    computeERC1155AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    computeERC20AssetType(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    computeERC721AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositFRA(
      _to: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositFRC1155(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositFRC20(
      _frc20: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositFRC721(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ledger_contract(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawAsset(
      _asset: PromiseOrValue<BytesLike>,
      _from: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFRA(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adminSetAsset(
      _asset_contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    adminSetLedger(
      _ledger_contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    asset_contract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    computeERC1155AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    computeERC20AssetType(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    computeERC721AssetType(
      addr: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositFRA(
      _to: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositFRC1155(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositFRC20(
      _frc20: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositFRC721(
      _addr: PromiseOrValue<string>,
      _to: PromiseOrValue<BytesLike>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ledger_contract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAsset(
      _asset: PromiseOrValue<BytesLike>,
      _from: PromiseOrValue<BytesLike>,
      _to: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFRA(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
