/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Burnable } from "./IERC20Burnable";
export type { IERC20Mintable } from "./IERC20Mintable";
export type { IPrismXXAsset } from "./IPrismXXAsset";
export type { IPrismXXLedger } from "./IPrismXXLedger";
