/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxySol from "./Proxy.sol";
export type { proxySol };
import type * as proxyAdminSol from "./ProxyAdmin.sol";
export type { proxyAdminSol };
export type { PrismXXAsset } from "./PrismXXAsset";
export type { PrismXXLedger } from "./PrismXXLedger";
