/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proxySol from "./Proxy.sol";
export * as proxyAdminSol from "./ProxyAdmin.sol";
export { PrismXXAsset__factory } from "./PrismXXAsset__factory";
export { PrismXXLedger__factory } from "./PrismXXLedger__factory";
