/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Burnable__factory } from "./IERC20Burnable__factory";
export { IERC20Mintable__factory } from "./IERC20Mintable__factory";
export { IPrismXXAsset__factory } from "./IPrismXXAsset__factory";
export { IPrismXXLedger__factory } from "./IPrismXXLedger__factory";
