/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as utils from "./utils";
export type { utils };
export type { IERC1155ReceiverUpgradeable } from "./IERC1155ReceiverUpgradeable";
export type { IERC1155Upgradeable } from "./IERC1155Upgradeable";
